run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.20'

# List from https://golangci-lint.run/usage/linters/
linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Other linters
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - stylecheck
    - tagalign
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - exportloopref

  disable:
    - canonicalheader
    - copyloopvar
    - cyclop
    - depguard
    - exhaustruct
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - goimports
    - gomoddirectives
    - inamedparam
    - intrange
    - maintidx
    - musttag
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - promlinter
    - protogetter
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - zerologlint

linters-settings:
  gci:
    sections:
      - standard
      - default
    skip-generated: false
    custom-order: true
  gosec:
    excludes:
      - G402 # InsecureSkipVerify
