version: "2"
run:
  modules-download-mode: readonly

# List from https://golangci-lint.run/usage/linters/
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - decorder
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
  disable:
    - bodyclose
    - canonicalheader
    - contextcheck # Re-enable in V2
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - exhaustruct
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - gomoddirectives
    - inamedparam
    - intrange
    - ireturn
    - maintidx
    - mnd
    - musttag
    - nestif # TODO: Re-enable in V2
    - nilnil
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - promlinter
    - protogetter
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagliatelle
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - zerologlint
  settings:
    gosec:
      excludes:
        - G402 # InsecureSkipVerify
        - G102 # Binds to all network interfaces
        - G403 # RSA keys should be at least 2048 bits
        - G115 # Integer overflow conversion (uint64 -> int64)
        - G404 # Use of weak random number generator (math/rand)
        - G204 # Subprocess launched with a potential tainted input or cmd arguments
        - G602 # Slice index out of range
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
        text: ifElseChain
      - linters:
          - lll
        source: '^// '
      - linters:
          - revive
        text: 'add-constant: '
      - linters:
          - revive
        text: 'unused-parameter: '
      - linters:
          - revive
        text: 'empty-block: '
      - linters:
          - revive
        text: 'var-naming: ' # TODO: Re-enable in V2
      - linters:
          - staticcheck
        text: ' should be ' # TODO: Re-enable in V2
      - linters:
          - staticcheck
        text: 'ST1003: should not use ALL_CAPS in Go names; use CamelCase instead'
    paths:
      - examples$
      - transport
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
